// Generated by CodiumAI

describe('getRecordForWorkout', () => {

});

    // Returns record for valid workoutId
    it('should return the record for a valid workoutId', () => {
      const req = {
        params: { workoutId: 'validWorkoutId' },
      };

      const res = {
        status: jest.fn().mockReturnThis(),
        send: jest.fn(),
      };

      recordService.getRecordForWorkout = jest.fn().mockReturnValue('record');

      getRecordForWorkout(req, res);

      expect(res.send).toHaveBeenCalledWith({ status: 'OK', data: 'record' });
    });

